bullmqWorkerConfig:
  pgConfig:
    host: 'localhost'
    port:  5432
    user: 'postgres'
    password: ''
    database: 'postgres'
    ssl: false

  redisConfig:
    host: 'localhost'
    port: 6379
    retry_timeout: 100
